# Working

In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("src/")

In [6]:

from src.data import get_track , getBatch
from src.model import PCT_Transformer
import glob
import numpy as np
import tensorflow as tf

In [7]:
aPaths = glob.glob("data/*AllPSA.npy")
hpaths = glob.glob("data/*.hits.npy")
ap = np.random.choice(aPaths)
hp = np.random.choice(hpaths)
trk =  get_track(apth=ap,hpth=hp)
batch = getBatch(trk,batch_size=32)
X = batch[:,:,2:5]
Y = batch[:,:,5:]
model = PCT_Transformer()

In [8]:
model.compile(optimizer = tf.keras.optimizers.Adam(),loss = tf.keras.losses.CategoricalCrossentropy(from_logits=False))

In [9]:
model.fit(X,Y)

Epoch:  0
Loss:  23.721388


(<tf.Tensor: shape=(), dtype=float32, numpy=23.721388>,
 <tf.Tensor: shape=(32, 3), dtype=float32, numpy=
 array([[0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.03980862, 0.49929404, 0.4608972 ],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.28908902, 0.41995385, 0.29095706],
        [0.03980862, 0.49929404, 0.4608972 ],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 , 0.2942406 , 0.48122323],
        [0.2245361 ,

# Experiment

In [43]:
predictions, loss = model(X,Y)

In [44]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=249.33801>